using System.Text;
using Microsoft.OpenApi;

namespace DotnetClientGenerator;

public class CSharpClientGenerator
{
    public string GenerateClient(ParsedApiSpec spec, ClientGeneratorOptions options)
    {
        StringBuilder sb = new();
        // Ensure generated files enable nullable annotations and include auto-generated header
        sb.AppendLine("#nullable enable");
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        string className = options.ClassName ?? "ApiClient";
        string namespaceName = options.Namespace ?? "GeneratedClient";

        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Net;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();

        GenerateModelClasses(sb, spec.Schemas);

        // Generate response types for each endpoint
        foreach (var endpoint in spec.Endpoints)
        {
            GenerateEndpointResponseType(sb, endpoint);
        }

        if (options.GenerateInterface)
        {
            GenerateInterface(sb, className, spec.Endpoints);
        }

        string interfaceImplementation = options.GenerateInterface ? $" : I{className}" : "";
        sb.AppendLine($"public class {className}{interfaceImplementation}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly HttpClient _httpClient;");
        sb.AppendLine("    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };");
        sb.AppendLine();
        sb.AppendLine($"    public {className}(HttpClient httpClient)");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClient = httpClient;");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var endpoint in spec.Endpoints)
        {
            GenerateEndpointMethod(sb, endpoint);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateEndpointResponseType(StringBuilder sb, ApiEndpoint endpoint)
    {
        string methodName = GenerateMethodName(endpoint);
        string responseTypeName = $"{methodName}Response";

        sb.AppendLine($"public abstract record {responseTypeName}");
        sb.AppendLine("{");

        foreach (var response in endpoint.Responses)
        {
            string statusName = GetStatusName(response.Key);
            string? responseModelType = GetResponseModelTypeFromResponse(response.Value);

            if (!string.IsNullOrEmpty(responseModelType))
            {
                sb.AppendLine($"    public sealed record {statusName}({responseModelType} Value) : {responseTypeName};");
            }
            else
            {
                sb.AppendLine($"    public sealed record {statusName} : {responseTypeName};");
            }
        }

        // Add Unexpected case for handling undefined status codes
        sb.AppendLine($"    public sealed record Unexpected(HttpStatusCode StatusCode, string Content) : {responseTypeName};");

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private string GetStatusName(string statusCode)
    {
        return statusCode switch
        {
            "200" => "Ok",
            "201" => "Created",
            "202" => "Accepted",
            "204" => "NoContent",
            "400" => "BadRequest",
            "401" => "Unauthorized",
            "403" => "Forbidden",
            "404" => "NotFound",
            "409" => "Conflict",
            "422" => "UnprocessableEntity",
            "500" => "InternalServerError",
            "502" => "BadGateway",
            "503" => "ServiceUnavailable",
            _ => $"Status{statusCode}"
        };
    }

    private string? GetResponseModelTypeFromResponse(IOpenApiResponse? response)
    {
        if (response?.Content == null)
            return null;

        var jsonContent = response.Content.FirstOrDefault(c => c.Key.Contains("json"));
        if (jsonContent.Value?.Schema == null) 
            return null;
        
        if (jsonContent.Value.Schema is OpenApiSchemaReference schemaRef)
            return schemaRef.Reference.Id;

        return GetCSharpTypeFromSchema(jsonContent.Value.Schema);
    }

    private void GenerateInterface(StringBuilder sb, string className, List<ApiEndpoint> endpoints)
    {
        sb.AppendLine($"public interface I{className}");
        sb.AppendLine("{");

        foreach (var endpoint in endpoints)
        {
            string methodName = GenerateMethodName(endpoint);
            bool hasRequestBody = endpoint.RequestBody?.Content?.Any() == true;

            List<string> parameters = new List<string>();

            foreach (var parameter in endpoint.Parameters)
            {
                string paramName = parameter.Name ?? "param";
                switch (parameter)
                {
                    case { In: ParameterLocation.Path }:
                        parameters.Add($"{GetCSharpTypeFromSchema(parameter.Schema)} {ToCamelCase(paramName)}");
                        break;
                    case { In: ParameterLocation.Query }:
                        parameters.Add($"{GetCSharpTypeFromSchema(parameter.Schema)}? {ToCamelCase(paramName)} = null");
                        break;
                }
            }

            if (hasRequestBody)
            {
                string requestBodyType = GetRequestBodyType(endpoint.RequestBody);
                parameters.Add($"{requestBodyType} body");
            }

            string parametersString = string.Join(", ", parameters);
            string returnType = $"Task<{methodName}Response>";

            sb.AppendLine($"    {returnType} {methodName}({parametersString});");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void GenerateEndpointMethod(StringBuilder sb, ApiEndpoint endpoint)
    {
        string methodName = GenerateMethodName(endpoint);
        string responseTypeName = $"{methodName}Response";
        string httpMethod = endpoint.Method.ToUpper() switch
        {
            "GET" => "HttpMethod.Get",
            "POST" => "HttpMethod.Post",
            "PUT" => "HttpMethod.Put",
            "DELETE" => "HttpMethod.Delete",
            "PATCH" => "HttpMethod.Patch",
            _ => "HttpMethod.Get"
        };

        bool hasRequestBody = endpoint.RequestBody?.Content?.Any() == true;

        List<string> parameters = new List<string>();
        List<string> pathParameters = new List<string>();

        foreach (var parameter in endpoint.Parameters)
        {
            string paramName = parameter.Name ?? "param";
            switch (parameter)
            {
                case { In: ParameterLocation.Path }:
                    pathParameters.Add(paramName);
                    parameters.Add($"{GetCSharpTypeFromSchema(parameter.Schema)} {ToCamelCase(paramName)}");
                    break;
                case { In: ParameterLocation.Query }:
                    parameters.Add($"{GetCSharpTypeFromSchema(parameter.Schema)}? {ToCamelCase(paramName)} = null");
                    break;
            }
        }

        if (hasRequestBody)
        {
            string requestBodyType = GetRequestBodyType(endpoint.RequestBody);
            parameters.Add($"{requestBodyType} body");
        }

        string parametersString = string.Join(", ", parameters);

        sb.AppendLine($"    public async Task<{responseTypeName}> {methodName}({parametersString})");
        sb.AppendLine("    {");

        string path = pathParameters.Aggregate(endpoint.Path, (current, pathParam) => current.Replace($"{{{pathParam}}}", $"{{{ToCamelCase(pathParam)}}}"));

        List<IOpenApiParameter> queryParams = endpoint.Parameters.Where(p => p.In == ParameterLocation.Query).ToList();
        if (queryParams.Any())
        {
            sb.AppendLine("        var queryParams = new List<string>();");
            foreach (var param in queryParams)
            {
                var paramName = ToCamelCase(param.Name ?? "param");
                sb.AppendLine($"        if ({paramName} != null)");
                sb.Append("            queryParams.Add($\"");
                sb.Append(param.Name);
                sb.Append("={");
                sb.Append(paramName);
                sb.AppendLine("}\");");
            }
            sb.AppendLine($"        var path = \"{path}\" + (queryParams.Any() ? \"?\" + string.Join(\"&\", queryParams) : \"\");");
        }
        else
        {
            sb.AppendLine($"        var path = $\"{path}\";");
        }

        sb.AppendLine();
        sb.AppendLine("        using var request = new HttpRequestMessage(" + httpMethod + ", path);");
        
        if (hasRequestBody)
        {
            sb.AppendLine("        request.Content = new StringContent(JsonSerializer.Serialize(body), Encoding.UTF8, \"application/json\");");
        }

        sb.AppendLine();
        sb.AppendLine("        using var response = await _httpClient.SendAsync(request);");
        sb.AppendLine("        var content = await response.Content.ReadAsStringAsync();");
        sb.AppendLine();
        sb.AppendLine("        return (int)response.StatusCode switch");
        sb.AppendLine("        {");

        foreach (var response in endpoint.Responses)
        {
            string statusName = GetStatusName(response.Key);
            string? responseModelType = GetResponseModelTypeFromResponse(response.Value);

            if (!string.IsNullOrEmpty(responseModelType))
            {
                sb.AppendLine($"            {response.Key} => new {responseTypeName}.{statusName}(JsonSerializer.Deserialize<{responseModelType}>(content, JsonOptions)!),");
            }
            else
            {
                sb.AppendLine($"            {response.Key} => new {responseTypeName}.{statusName}(),");
            }
        }

        sb.AppendLine($"            _ => new {responseTypeName}.Unexpected(response.StatusCode, content)");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private string GenerateMethodName(ApiEndpoint endpoint)
    {
        if (!string.IsNullOrEmpty(endpoint.OperationId))
        {
            return ToPascalCase(endpoint.OperationId);
        }

        var pathParts = endpoint.Path.Split('/', StringSplitOptions.RemoveEmptyEntries)
            .Where(part => !part.StartsWith("{"))
            .ToArray();

        var cleanPath = string.Join("", pathParts.Select(ToPascalCase));
        return $"{ToPascalCase(endpoint.Method.ToLower())}{cleanPath}";
    }

    private string ToCamelCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        return char.ToLowerInvariant(input[0]) + input[1..];
    }

    private string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        return char.ToUpperInvariant(input[0]) + input[1..];
    }

    private void GenerateModelClasses(StringBuilder sb, IDictionary<string, OpenApiSchema?> schemas)
    {
        foreach (var schema in schemas)
        {
            if (schema.Value != null)
            {
                GenerateModelClass(sb, schema.Key, schema.Value);
                sb.AppendLine();
            }
        }
    }

    private void GenerateModelClass(StringBuilder sb, string className, OpenApiSchema schema)
    {
        sb.AppendLine($"public class {className}");
        sb.AppendLine("{");

        if (schema.Properties != null)
        {
            foreach (var property in schema.Properties)
            {
                var propertyName = ToPascalCase(property.Key);
                var propertyType = GetCSharpTypeFromSchema(property.Value);
                var isRequired = schema.Required?.Contains(property.Key) == true;
                
                if (!isRequired && !propertyType.EndsWith("?") && IsNullableType(property.Value))
                {
                    propertyType += "?";
                }

                sb.AppendLine($"    public {propertyType} {propertyName} {{ get; set; }}");
            }
        }

        sb.AppendLine("}");
    }

    private string GetCSharpTypeFromSchema(IOpenApiSchema? schema)
    {
        switch (schema)
        {
            case null:
            {
                return "object";
            }
            case OpenApiSchemaReference schemaRef:
                return schemaRef.Reference.Id ?? "object";
        }

        OpenApiSchema? openApiSchema = schema as OpenApiSchema;
        if (openApiSchema == null)
            return "object";

        if (openApiSchema.Type != JsonSchemaType.Array || openApiSchema.Items == null)
            return openApiSchema.Type switch
            {
                JsonSchemaType.String => openApiSchema.Format switch
                {
                    "date-time" => "DateTime",
                    "date" => "DateOnly",
                    "time" => "TimeOnly",
                    "uuid" => "Guid",
                    _ => "string"
                },
                JsonSchemaType.Integer => openApiSchema.Format switch
                {
                    "int64" => "long",
                    _ => "int"
                },
                JsonSchemaType.Number => openApiSchema.Format switch
                {
                    "float" => "float",
                    "double" => "double",
                    _ => "decimal"
                },
                JsonSchemaType.Boolean => "bool",
                _ => "object"
            };
        string itemType = GetCSharpTypeFromSchema(openApiSchema.Items);
        return $"List<{itemType}>";

    }

    private static bool IsNullableType(IOpenApiSchema? schema)
    {
        if (schema == null)
        {
            return false;
        }

        OpenApiSchema? openApiSchema = schema as OpenApiSchema;
        return openApiSchema == null
            ? schema is OpenApiSchemaReference
            : // References are nullable
            openApiSchema.Type switch
            {
                JsonSchemaType.String => true,
                JsonSchemaType.Object => true,
                JsonSchemaType.Array => true,
                _ => false
            };
    }

    private string GetRequestBodyType(OpenApiRequestBody? requestBody)
    {
        if (requestBody?.Content == null)
            return "object";

        KeyValuePair<string, IOpenApiMediaType> jsonContent = requestBody.Content.FirstOrDefault(c => c.Key.Contains("json"));
        if (jsonContent.Value?.Schema == null) return "object";
        if (jsonContent.Value.Schema is OpenApiSchemaReference schemaRef)
        {
            return schemaRef.Reference.Id ?? "object";
        }

        return GetCSharpTypeFromSchema(jsonContent.Value.Schema);
    }

    private string GetResponseType(OpenApiResponses responses)
    {
        string responseModelType = GetResponseModelType(responses);
        return !string.IsNullOrEmpty(responseModelType) ? $"Task<ApiResponse<{responseModelType}>>" : "Task<ApiResponse>";
    }

    private string GetResponseModelType(OpenApiResponses responses)
    {
        var successResponse = responses.FirstOrDefault(r => r.Key.StartsWith("2"));
        if (successResponse.Value?.Content == null)
            return string.Empty;

        KeyValuePair<string, IOpenApiMediaType> jsonContent = successResponse.Value.Content.FirstOrDefault(c => c.Key.Contains("json"));
        if (jsonContent.Value?.Schema == null) return string.Empty;
        if (jsonContent.Value.Schema is OpenApiSchemaReference schemaRef)
        {
            return schemaRef.Reference.Id ?? string.Empty;
        }

        return GetCSharpTypeFromSchema(jsonContent.Value.Schema);

    }
}
